# Generated by Django 5.2 on 2025-05-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_link1_post_link2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link2',
        ),
    ]
