# Generated by Django 5.2 on 2025-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_link1_remove_post_link2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
