# Generated by Django 5.2.1 on 2026-05-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_approvedtagauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('parent_category', models.CharField(blank=True, max_length=100)),
                ('grandparent_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_tags', to='post.post')),
            ],
        ),
    ]
