# Generated by Django 5.2.1 on 2026-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_semantictag'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantictag',
            name='semantic_labels',
            field=models.TextField(blank=True, default=''),
        ),
    ]
