# Generated by Django 5.2.1 on 2026-05-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_semantictag_semantic_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('parent_category', models.CharField(blank=True, max_length=100)),
                ('grandparent_category', models.CharField(blank=True, max_length=100)),
                ('semantic_labels', models.TextField(blank=True, default='')),
                ('click_count', models.IntegerField(default=1)),
                ('last_clicked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-click_count', '-last_clicked'],
                'unique_together': {('user', 'entity')},
            },
        ),
    ]
