# Generated by Django 5.2.1 on 2026-05-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_bannerad'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
