# Generated by Django 5.2.1 on 2026-08-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_readtimelog_writewordlookuplog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writewordlookuplog',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadTimeLog',
        ),
        migrations.DeleteModel(
            name='WritewordLookupLog',
        ),
    ]
