# Generated by Django 5.2.1 on 2026-05-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_userprofile_profile_favorites_alter_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
