# Generated by Django 5.2.1 on 2026-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_readtimelog_writewordlookuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewwritinglog',
            name='issues_detail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
