# Generated by Django 5.2.1 on 2026-08-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_reviewwritinglog_issues_detail'),
        ('post', '0017_remove_writewordlookuplog_user_delete_readtimelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_by', to='post.post'),
        ),
    ]
